language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.1
  - 7.2

install:
  - composer install

# `precise` must be used until the plugin drops support for PHP 5.3
# as `trusty` does not support this version
sudo: required
dist: precise

script: phpunit
